<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Product.proto

namespace Services;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>services.ProductResponse</code>
 */
class ProductResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 prod_stock = 1;</code>
     */
    protected $prod_stock = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $prod_stock
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Product::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 prod_stock = 1;</code>
     * @return int
     */
    public function getProdStock()
    {
        return $this->prod_stock;
    }

    /**
     * Generated from protobuf field <code>int32 prod_stock = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setProdStock($var)
    {
        GPBUtil::checkInt32($var);
        $this->prod_stock = $var;

        return $this;
    }

}

