<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Product.proto

namespace Services;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>services.ProductRequest</code>
 */
class ProductRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 prod_id = 1;</code>
     */
    protected $prod_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $prod_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Product::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 prod_id = 1;</code>
     * @return int
     */
    public function getProdId()
    {
        return $this->prod_id;
    }

    /**
     * Generated from protobuf field <code>int32 prod_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setProdId($var)
    {
        GPBUtil::checkInt32($var);
        $this->prod_id = $var;

        return $this;
    }

}

